server:
  port: 9003

spring:
  datasource:
    dynamic:
      druid:
        filters: stat
        initial-size: 5
        min-idle: 5
        max-active: 200
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/mall_sms?useSSL=false&serverTimezone=Hongkong&useUnicode=true
          username: root
          password: 123456
          type: com.alibaba.druid.pool.DruidDataSource
          driverClassName: com.mysql.cj.jdbc.Driver
          initialSize: 5
          minIdle: 5
          maxActive: 200
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 30000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.order.entity

seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: "SEATA_GROUP"
      username: "nacos"
      password: "nacos"
      namespace: public
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: "SEATA_GROUP"
      username: "nacos"
      password: "nacos"
      namespace: public
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      my_test_tx_group: default
  enabled: true