server:
  port: 7600


bobo:
  redisson:
    host: localhost
    port: 6379
    timeout: 1
    ssl: false

spring:
  cache:
    type: REDIS
    redis:
      time-to-live: 60000

# 修改日志等级\
logging:
  config: classpath:logback-spring.xml
  level:
    com.example.basicspring.service: debug
