server:
  port: 8070
spring:
  application:
    name: nacos-config
  cloud:
    nacos:
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        file-extension: properties
      discovery:
        server-addr: 127.0.0.1:8848
        username: ${spring.application.name}

